/**
 * Dependencies
 */

const tokens = require('./tokens.js');
const logical = require('tailwindcss-logical');

/**
 * Config
 */

module.exports = {
  version: 'v2',
  documentation: 'https://tailwindcss.com',
  important: true,
  purge: false,
  theme: {
    borderWidth: tokens.borderWidth,
    borderRadius: tokens.borderRadius,
    boxShadow: tokens.boxShadow,
    colors: {
      ...tokens.colors,
      DEFAULT: ''
    },
    fill: tokens.colors,
    stroke: tokens.colors,
    fontFamily: tokens.fontFamily,
    fontSize: tokens.fontSize,
    lineHeight: tokens.lineHeight,
    maxWidth: tokens.maxWidth,
    screens: {
      'desktop': `${tokens.screens['desktop']}px`,
      'tablet': `${tokens.screens['tablet']}px`,
      'mobile': `${tokens.screens['mobile']}px`,
      'small': `${tokens.screens['small']}px`
    },
    spacing: tokens.spacing,
    width: tokens.width,
    margin: {
      ...tokens.spacing,
      '-2': '-16px',
      '-1': '-8px',
      'auto': 'auto'
    }
  },
  plugins: [
    logical
  ],
  variants: {
    // preflight: [],
    // container: [],
    accessibility: ['responsive'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    animation: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundClip: [],
    backgroundColor: ['hover', 'focus'],
    backgroundImage: [],
    backgroundOpacity: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['hover', 'focus'],
    borderOpacity: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: [],
    clear: [],
    cursor: [],
    display: ['responsive'],
    divideColor: [],
    divideOpacity: [],
    divideStyle: [],
    divideWidth: [],
    fill: [],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: [],
    fontFamily: [],
    fontSize: ['responsive'],
    fontSmoothing: [],
    fontStyle: [],
    fontVariantNumeric: [],
    fontWeight: [],
    gap: ['responsive'],
    gradientColorStops: [],
    gridAutoColumns: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridAutoRows: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridColumnStart: ['responsive'],
    gridRow: ['responsive'],
    gridRowEnd: ['responsive'],
    gridRowStart: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridTemplateRows: ['responsive'],
    height: [],
    inset: [],
    justifyContent: ['responsive'],
    justifyItems: [],
    justifySelf: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    logical: ['responsive'],
    margin: ['responsive'],
    maxHeight: [],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: ['responsive'],
    outline: [],
    overflow: ['responsive'],
    overscrollBehavior: [],
    padding: ['responsive'],
    placeContent: [],
    placeholderColor: [],
    placeholderOpacity: [],
    placeItems: [],
    placeSelf: [],
    pointerEvents: [],
    position: [],
    resize: [],
    // ringColor: [],
    // ringOffsetColor: [],
    // ringOffsetWidth: [],
    // ringOpacity: [],
    // ringWidth: [],
    rotate: [],
    scale: [],
    skew: [],
    space: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: ['responsive'],
    textColor: ['hover', 'focus'],
    textDecoration: [],
    textOpacity: [],
    textOverflow: [],
    textTransform: [],
    transform: [],
    transformOrigin: [],
    transitionDelay: [],
    transitionDuration: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    translate: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: ['responsive'],
    wordBreak: [],
    zIndex: [],
  },
  corePlugins: [
    // 'preflight',
    // 'container',
    'accessibility',
    'alignContent',
    'alignItems',
    'alignSelf',
    'animation',
    'appearance',
    'backgroundAttachment',
    'backgroundClip',
    'backgroundColor',
    'backgroundImage',
    'backgroundOpacity',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundSize',
    'borderCollapse',
    'borderColor',
    'borderOpacity',
    'borderRadius',
    'borderStyle',
    'borderWidth',
    'boxShadow',
    'boxSizing',
    'clear',
    'cursor',
    'display',
    'divideColor',
    'divideOpacity',
    'divideStyle',
    'divideWidth',
    'fill',
    'flex',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'float',
    'fontFamily',
    'fontSize',
    'fontSmoothing',
    'fontStyle',
    'fontVariantNumeric',
    'fontWeight',
    'gap',
    'gradientColorStops',
    'gridAutoColumns',
    'gridAutoFlow',
    'gridAutoRows',
    'gridColumn',
    'gridColumnEnd',
    'gridColumnStart',
    'gridRow',
    'gridRowEnd',
    'gridRowStart',
    'gridTemplateColumns',
    'gridTemplateRows',
    'height',
    'inset',
    'justifyContent',
    'justifyItems',
    'justifySelf',
    'letterSpacing',
    'lineHeight',
    'listStylePosition',
    'listStyleType',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'objectFit',
    'objectPosition',
    'opacity',
    'order',
    'outline',
    'overflow',
    'overscrollBehavior',
    'padding',
    'placeContent',
    'placeholderColor',
    'placeholderOpacity',
    'placeItems',
    'placeSelf',
    'pointerEvents',
    'position',
    'resize',
    // 'ringColor',
    // 'ringOffsetColor',
    // 'ringOffsetWidth',
    // 'ringOpacity',
    // 'ringWidth',
    'space',
    'stroke',
    'strokeWidth',
    'tableLayout',
    'textAlign',
    'textColor',
    'textDecoration',
    'textOpacity',
    'textOverflow',
    'textTransform',

    // Transform needs to be the first module before other translate modules
    'transform',
    'transformOrigin',
    'translate',
    'rotate',
    'scale',
    'skew',

    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    'width',
    'wordBreak',
    'zIndex',
  ],
  prefixes: {
    borderWidth : 'border',
    borderRadius: 'rounded',
    boxShadow: 'shadow',
    colors: 'bg',
    stroke: 'stroke',
    fill: 'fill',
    fontFamily: 'font',
    fontSize: 'text',
    lineHeight: 'leading',
    maxWidth: 'max-w',
    screens: false,
    spacing: 'p',
    width: 'w',
    margin: 'm',
  },
  descriptions: {
    'preflight': 'Tailwind\'s base/reset styles.',
    'container': 'The container component.',
    'accessibility': 'The sr-only and not-sr-only utilities.',
    'alignContent': 'The align-content utilities like content-end.',
    'alignItems': 'The align-items utilities like items-center.',
    'alignSelf': 'The align-self utilities like self-end.',
    'animation': 'The animation utilities like animate-none.',
    'appearance': 'The appearance utilities like appearance-none.',
    'backgroundAttachment': 'The background-attachment utilities like bg-local.',
    'backgroundClip': 'The background-clip utilities like bg-clip-padding.',
    'backgroundColor': 'The background-color utilities like bg-green-700.',
    'backgroundImage': 'The background-image utilities like bg-gradient-to-br.',
    'backgroundOpacity': 'The background-color opacity utilities like bg-opacity-25.',
    'backgroundPosition': 'The background-position utilities like bg-left-top.',
    'backgroundRepeat': 'The background-repeat utilities like bg-repeat-x.',
    'backgroundSize': 'The background-size utilities like bg-cover.',
    'borderCollapse': 'The border-collapse utilities like border-collapse.',
    'borderColor': 'The border-color utilities like border-green-700.',
    'borderOpacity': 'The border-color opacity utilities like border-opacity-25.',
    'borderRadius': 'The border-radius utilities like rounded.',
    'borderStyle': 'The border-style utilities like border-dotted.',
    'borderWidth': 'The border-width utilities like border-l-2.',
    'boxShadow': 'The box-shadow utilities like shadow-up.',
    'boxSizing': 'The box-sizing utilities like box-border.',
    'clear': 'The clear utilities like clear-right.',
    'colors': 'The color utilities using design tokens for backgrounds (bg-), text (text-), border (border-), divide (divide-), and ring (ring-).',
    'cursor': 'The cursor utilities like cursor-wait.',
    'display': 'The display utilities like table-column-group.',
    'divideColor': 'The between elements border-color utilities like divide-gray-500.',
    'divideOpacity': 'The divide-opacity utilities like divide-opacity-50.',
    'divideStyle': 'The divide-style utilities like divide-dotted.',
    'divideWidth': 'The between elements border-width utilities like divide-x-2.',
    'fill': 'The fill utilities like fill-current.',
    'flex': 'The flex utilities like flex-auto.',
    'flexDirection': 'The flex-direction utilities like flex-row-reverse.',
    'flexGrow': 'The flex-grow utilities like flex-grow-0.',
    'flexShrink': 'The flex-shrink utilities like flex-shrink-0.',
    'flexWrap': 'The flex-wrap utilities like flex-wrap-reverse.',
    'float': 'The float utilities like float-left.',
    'fontFamily': 'The font-family utilities like font-default. Use the Type Utilities to use combined font attributes that include size, family, and line-height.',
    'fontSize': 'The font-size utilities like text-h1. Use the Type Utilities to use combined font attributes that include size, family, and line-height.',
    'fontSmoothing': 'The font-smoothing utilities like antialiased.',
    'fontStyle': 'The font-style utilities like italic.',
    'fontVariantNumeric': 'The font-variant-numeric utilities like lining-nums.',
    'fontWeight': 'The font-weight utilities like font-bold.',
    'gap': 'The gap utilities like gap-x-28.',
    'gradientColorStops': 'The gradient-color-stops utilities like via-green-700.',
    'gridAutoColumns': 'The grid-auto-columns utilities like auto-cols-min.',
    'gridAutoFlow': 'The grid-auto-flow utilities like grid-flow-col.',
    'gridAutoRows': 'The grid-auto-rows utilities like auto-rows-min.',
    'gridColumn': 'The grid-column utilities like col-span-6.',
    'gridColumnEnd': 'The grid-column-end utilities like col-end-7.',
    'gridColumnStart': 'The grid-column-start utilities like col-start-7.',
    'gridRow': 'The grid-row utilities like row-span-3.',
    'gridRowEnd': 'The grid-row-end utilities like row-end-4.',
    'gridRowStart': 'The grid-row-start utilities like row-start-4.',
    'gridTemplateColumns': 'The grid-template-columns utilities like grid-cols-7.',
    'gridTemplateRows': 'The grid-template-rows utilities like grid-rows-4.',
    'height': 'The height utilities like h-64.',
    'inset': 'The inset utilities like bottom-10.',
    'justifyContent': 'The justify-content utilities like justify-center.',
    'justifyItems': 'The justify-items utilities like justify-items-end.',
    'justifySelf': 'The justify-self utilities like justify-self-end.',
    'letterSpacing': 'The letter-spacing utilities like tracking-normal.',
    'lineHeight': 'The line-height utilities like leading-h1. Use the Type Utilities to use combined font attributes that include size, family, and line-height.',
    'listStylePosition': 'The list-style-position utilities like list-inside.',
    'listStyleType': 'The list-style-type utilities like list-disc.',
    'margin': 'The margin utilities like ml-6.',
    'maxHeight': 'The max-height utilities like max-h-32.',
    'maxWidth': 'The max-width utilities like max-w-900.',
    'minHeight': 'The min-height utilities like min-h-full.',
    'minWidth': 'The min-width utilities like min-w-full.',
    'objectFit': 'The object-fit utilities like object-fill.',
    'objectPosition': 'The object-position utilities like object-left-top.',
    'opacity': 'The opacity utilities like opacity-50.',
    'order': 'The order utilities like order-8.',
    'outline': 'The outline utilities like outline-white.',
    'overflow': 'The overflow utilities like overflow-y-auto.',
    'overscrollBehavior': 'The overscroll-behavior utilities like overscroll-y-contain.',
    'padding': 'The padding utilities like pr-4.',
    'placeContent': 'The place-content utilities like place-content-between.',
    'placeholderColor': 'The placeholder color utilities like placeholder-red-600.',
    'placeholderOpacity': 'The placeholder color opacity utilities like placeholder-opacity-25.',
    'placeItems': 'The place-items utilities like place-items-end.',
    'placeSelf': 'The place-self utilities like place-self-end.',
    'pointerEvents': 'The pointer-events utilities like pointer-events-none.',
    'position': 'The position utilities like absolute.',
    'resize': 'The resize utilities like resize-y.',
    'ringColor': 'The ring-color utilities like ring-green-700.',
    'ringOffsetColor': 'The ring-offset-color utilities like ring-offset-green-700.',
    'ringOffsetWidth': 'The ring-offset-width utilities like ring-offset-2.',
    'ringOpacity': 'The ring-opacity utilities like ring-opacity-50.',
    'ringWidth': 'The ring-width utilities like ring-2.',
    'rotate': 'The rotate utilities like rotate-180.',
    'scale': 'The scale utilities like scale-x-95.',
    'screens': 'The breakpoints for responsive variants. These will apply to core plugins with "responsive" in the variant list below.',
    'skew': 'The skew utilities like -skew-x-1.',
    'space': 'The "space-between" utilities like space-x-4.',
    'spacing': 'This determines the spacing scale inherited by the padding, margin, width, height, maxHeight, gap, inset, space, and translate core plugins.',
    'stroke': 'The stroke utilities like stroke-current.',
    'strokeWidth': 'The stroke-width utilities like stroke-1.',
    'tableLayout': 'The table-layout utilities like table-auto.',
    'textAlign': 'The text-align utilities like text-center.',
    'textColor': 'The text-color utilities like text-green-700.',
    'textDecoration': 'The text-decoration utilities like line-through.',
    'textOpacity': 'The text-opacity utilities like text-opacity-50.',
    'textOverflow': 'The text-overflow utilities like overflow-ellipsis.',
    'textTransform': 'The text-transform utilities like lowercase.',
    'transform': 'The transform utility (for enabling transform features).',
    'transformOrigin': 'The transform-origin utilities like origin-bottom-right.',
    'transitionDelay': 'The transition-delay utilities like delay-200.',
    'transitionDuration': 'The transition-duration utilities like duration-200.',
    'transitionProperty': 'The transition-property utilities like transition-colors.',
    'transitionTimingFunction': 'The transition-timing-function utilities like ease-in.',
    'translate': 'The translate utilities like -translate-x-full.',
    'userSelect': 'The user-select utilities like select-text.',
    'verticalAlign': 'The vertical-align utilities like align-middle.',
    'visibility': 'The visibility utilities like visible.',
    'whitespace': 'The whitespace utilities like whitespace-pre.',
    'width': 'The width utilities like w-900.',
    'wordBreak': 'The word-break utilities like break-words.',
    'zIndex': 'The z-index utilities like z-30.',
  }
};
