/**
 * Dependencies
 */

// const defaultConfig = require('tailwindcss/defaultConfig')();
const variables = require('./variables.js');

/**
 * Config
 */

module.exports = {
  options: {
    prefix: '',
    important: false,
    separator: ':'
  },
  theme: {
    colors: variables.colors,
    fonts: variables.fonts,
    fontFamily: variables.fontFamily,
    fontWeight: variables.fontWeight,
    fontSize: variables.fontSize,
    lineHeight: variables.lineHeight,
    backgroundColor: variables.colors,
    borderWidth: variables.borderWidth,
    borderColor: global.Object.assign({ default: '' }, variables.colors),
    boxShadow: variables.boxShadow,
    margin: variables.margin,
    padding: variables.padding,
    maxWidth: variables.maxWidth,
    screens: {
      'screen-desktop': `${variables.screens['screen-desktop']}px`,
      'screen-tablet': `${variables.screens['screen-tablet']}px`,
      'screen-mobile': `${variables.screens['screen-mobile']}px`,
      'screen-sm-mobile': `${variables.screens['screen-desktop']}px`
    },
    textColor: variables.colors
  },
  variants: {
    preflight: [],
    container: [],
    accessibility: ['responsive'],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ['hover', 'focus'],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['hover', 'focus'],
    borderRadius: [],
    borderStyle: [],
    borderWidth: ['responsive'],
    cursor: [],
    display: ['responsive'],
    flexDirection: ['responsive'],
    flexWrap: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    justifyContent: ['responsive'],
    alignContent: ['responsive'],
    flex: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    order: ['responsive'],
    float: [],
    fontFamily: [],
    fontWeight: [],
    height: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: ['responsive'],
    maxHeight: [],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    outline: [],
    overflow: ['responsive'],
    padding: ['responsive'],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    inset: [],
    resize: [],
    boxShadow: ['responsive'],
    fill: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: ['hover', 'focus'],
    fontSize: ['responsive'],
    fontStyle: [],
    textTransform: [],
    textDecoration: [],
    fontSmoothing: [],
    letterSpacing: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    wordBreak: [],
    width: [],
    zIndex: []
  },
  /**
   * These are the plugins that will be enabled in the process utilitiy stylesheet
   */
  corePlugins: [
    // 'preflight',
    // 'container',
    'accessibility',
    // 'appearance',
    // 'backgroundAttachment',
    'backgroundColor',
    // 'backgroundPosition',
    // 'backgroundRepeat',
    // 'backgroundSize',
    // 'borderCollapse',
    'borderColor',
    'borderRadius',
    // 'borderStyle',
    'borderWidth',
    'cursor',
    'display',
    'flexDirection',
    'flexWrap',
    'alignItems',
    'alignSelf',
    'justifyContent',
    'alignContent',
    'flex',
    'flexGrow',
    'flexShrink',
    'order',
    // 'float',
    'fontFamily',
    'fontWeight',
    'height',
    // 'lineHeight',
    // 'listStylePosition',
    'listStyleType',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    // 'objectFit',
    // 'objectPosition',
    // 'opacity',
    // 'outline',
    'overflow',
    'padding',
    // 'placeholderColor',
    'pointerEvents',
    'position',
    'inset',
    // 'resize',
    'boxShadow',
    'fill',
    'stroke',
    // 'tableLayout',
    'textAlign',
    'textColor',
    'fontSize',
    'fontStyle',
    'textTransform',
    'textDecoration',
    'fontSmoothing',
    // 'letterSpacing',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    // 'wordBreak',
    // 'width',
    'zIndex'
  ]
};
